Create Database Customer_Shopping_Behavior_Analysis;

USE  Customer_Shopping_Behavior_Analysis;

select * from Customer;


--  What is the total revenue generated by male vs. female customers?

SELECT 
    gender AS Gender, SUM(purchase_amount) AS 'Total Revenue'
FROM
    Customer
GROUP BY gender;


--  Which customers used a discount but still spent more than the average purchase amount?

SELECT 
    customer_id, purchase_amount
FROM
    Customer
WHERE
    discount_applied = 'Yes'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount)
        FROM
            Customer);
            
--  Which are the top 5 products with the highest average review rating?

SELECT 
    item_purchased AS 'Top 5 Products',
    ROUND(AVG(review_rating), 2) AS 'Average Review Rating'
FROM
    Customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

--  Compare the average purchase amounts between Standard and Express Shipping.

select shipping_type as 'Shipping Type', round(avg(purchase_amount), 2) as 'Average Purchase Amount'
from Customer
where shipping_type in ('Express', 'Standard')
group by shipping_type;

--  Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT 
    subscription_status AS 'Subscription Status',
    count(customer_id) as 'Customer Count',
    SUM(purchase_amount) AS 'Total Revenue',
    ROUND(AVG(purchase_amount), 2) AS 'Average Purchase Amount'
FROM
    Customer
GROUP BY subscription_status
ORDER BY SUM(purchase_amount) DESC;

--  Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
    item_purchased AS 'Products with highest POP',
    ROUND(100 * SUM(CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END) / COUNT(*),
            2) AS Discount_Rate
FROM
    Customer
GROUP BY item_purchased
ORDER BY Discount_Rate DESC
LIMIT 5;


--  Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

with Customer_type as (

	select customer_id, previous_purchases, 
    case when previous_purchases = 1 then 'New'
    when previous_purchases >= 2 and previous_purchases <= 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
    from Customer

)

select customer_segment, count(*) as Customers_count 
from Customer_type 
group by customer_segment;

--  What are the top 3 most purchased products within each category?

with Products_rank as (

		select category, item_purchased, sum(purchase_amount) as Total_Revenue,
        row_number() over (partition by category order by sum(purchase_amount) desc) as product_rank
        from Customer
        group by category, item_purchased

)

SELECT 
    product_rank, category, item_purchased, Total_revenue
FROM
    Products_rank
WHERE
    product_rank <= 3
ORDER BY Total_revenue DESC;

--  Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT 
    subscription_status, COUNT(*) AS count_of_customers
FROM
    Customer
WHERE
    previous_purchases >= 5
GROUP BY subscription_status
ORDER BY count_of_customers DESC;

--  What is the revenue contribution of each age group?

SELECT 
    age_group AS 'Age Group',
    SUM(purchase_amount) AS Total_revenue,
    ROUND(100 * SUM(purchase_amount) / (SELECT 
                    SUM(purchase_amount)
                FROM
                    Customer),
            2) AS Revenue_Contribution
FROM
    Customer
GROUP BY age_group
ORDER BY Revenue_Contribution DESC;



select * from Customer
limit 3900;












